// Code generated by reset.gen.
package model

func (p *Request) Reset() {
	if p == nil {
		return
	}

	p.Full = ""
}

func (p *Response) Reset() {
	if p == nil {
		return
	}

	p.Short = ""
}

func (p *ShortItem) Reset() {
	if p == nil {
		return
	}

	p.Corr = ""
	p.Short = ""
}

func (p *FullItem) Reset() {
	if p == nil {
		return
	}

	p.Corr = ""
	p.Full = ""
}

func (p *StoreItem) Reset() {
	if p == nil {
		return
	}

	p.Short = ""
	p.Full = ""
}

func (p *AuditData) Reset() {
	if p == nil {
		return
	}

	p.Created = 0
	p.Action = ""
	p.User = ""
	p.Address = ""
}
