/*
Package main генерация метода Reset() для структур с меткой // generate:reset.

Запуск:

	go run ./cmd/reset

Алгоритм:
1. Сканирует все пакеты начиная с корня
2. Для каждой структуры с комментарием // generate:reset
3. Генерирует метод Reset()
4. Сохраняет в reset.gen.go в том же пакете
*/
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const resetTemplate = `// Code generated by reset.gen.
package {{.Package}}

{{range .Structs}}
func (p *{{.Name}}) Reset() {
	if p == nil {
		return
	}
{{range .Fields}}
	{{fieldReset "p." .Name .Type}}
{{- end}}
}
{{end}}
`

// generate:reset
type FieldInfo struct {
	Name string
	Type ast.Expr
}

// generate:reset
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

func main() {
	fmt.Println("generating reset methods")

	if err := processPath("./..."); err != nil {
		fmt.Println("ошибка генерации: ", err.Error())
		return
	}
	fmt.Println("файлы сгенерированы успешно")
}

// processPath парсинг файлов пакета
func processPath(path string) error {

	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypesInfo,
		Tests: false,
	}
	pkgs, err := packages.Load(cfg, path)
	if err != nil {
		return err
	}

	var structs []StructInfo
	var resultErr error

	for _, pkg := range pkgs {
		for _, file := range pkg.GoFiles {

			astFile, err := parser.ParseFile(token.NewFileSet(), file, nil, parser.ParseComments)
			if err != nil {
				continue
			}

			ast.Inspect(astFile, func(n ast.Node) bool {
				gen, ok := n.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					return true
				}

				//  ищем комментарий generate:reset
				if gen.Doc == nil || !strings.Contains(gen.Doc.Text(), "generate:reset") {

					return true
				}

				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					info := StructInfo{Name: ts.Name.Name}
					for _, field := range st.Fields.List {
						for _, name := range field.Names {
							info.Fields = append(info.Fields, FieldInfo{
								Name: name.Name,
								Type: field.Type,
							})
						}
					}
					structs = append(structs, info)
				}
				return true
			})
		}
		if len(structs) > 0 {
			if err := generateFile(pkg.Dir, pkg.Name, structs); err != nil {
				resultErr = errors.Join(resultErr, err)
			}
			structs = structs[:0]
		}
	}
	return resultErr
}

// generateFile создание файла по шаблону
func generateFile(dir, pkg string, structs []StructInfo) error {
	funcMap := template.FuncMap{
		"fieldReset": fieldReset,
	}

	tmpl, _ := template.New("reset").Funcs(funcMap).Parse(resetTemplate)

	data := struct {
		Package string
		Structs []StructInfo
	}{
		Package: pkg,
		Structs: structs,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	// Форматируем код
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("format error: ", err.Error())
		formatted = buf.Bytes()
	}

	path := filepath.Join(dir, "reset.gen.go")
	os.WriteFile(path, formatted, 0644)
	fmt.Println("generated ", path)
	return nil
}

// fieldReset сброс к дефолтовым значениям
func fieldReset(pointer, name string, expr ast.Expr) string {
	x := pointer + name

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return string(fmt.Sprintf("%s = \"\"", x))
		case "bool":
			return fmt.Sprintf("%s = false", x)
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return fmt.Sprintf("%s = 0", x)
		default:
			// Для именованных типов вызываем Reset
			return fmt.Sprintf(`if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil { v.Reset() }`, x)
		}

	case *ast.ArrayType:
		return fmt.Sprintf("%s = %s[:0]", x, x)

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", x)

	case *ast.StarExpr:
		// Рекурсивно обрабатываем указатель
		inner := fieldReset("*"+x, "", t.X)
		return fmt.Sprintf("if %s != nil { %s }", x, inner)

	case *ast.SelectorExpr:
		return fmt.Sprintf(`if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil {v.Reset()}`, x)

	default:
		return ""
	}
}
