// Code generated by reset.gen.
package main

func (p *FieldInfo) Reset() {
	if p == nil {
		return
	}

	p.Name = ""
	if v, ok := (any)(p.Type).(interface{ Reset() }); ok && v != nil {
		v.Reset()
	}
}

func (p *StructInfo) Reset() {
	if p == nil {
		return
	}

	p.Name = ""
	p.Fields = p.Fields[:0]
}
